import yfinance as yf
import json
import os
import tempfile

def generate_stock_dashboard(ticker: str, period: str = "1mo") -> str:
    """Generate an interactive standalone HTML dashboard for a stock and save it locally."""
    try:
        stock = yf.Ticker(ticker)
        hist = stock.history(period=period)
        
        if hist.empty:
            return f"Error: No historical data found for {ticker} over period {period}."
            
        # Prepare data securely for Chart.js
        dates = hist.index.strftime('%Y-%m-%d').tolist()
        closes = [round(x, 2) for x in hist['Close'].tolist()]
        
        html_content = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{ticker} Interactive Dashboard</title>
            <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
            <style>
                body {{ font-family: 'Segoe UI', system-ui, sans-serif; padding: 2rem; background: #0f172a; color: #f8fafc; margin: 0; }}
                .container {{ max-width: 1200px; margin: 0 auto; background: #1e293b; padding: 2rem; border-radius: 12px; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.5); }}
                h1 {{ margin-top: 0; color: #38bdf8; border-bottom: 1px solid #334155; padding-bottom: 1rem; }}
                .chart-wrapper {{ position: relative; height: 60vh; width: 100%; margin-top: 1.5rem; }}
                .footer {{ margin-top: 1.5rem; text-align: center; color: #64748b; font-size: 0.875rem; }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>📈 {ticker} Stock Performance ({period})</h1>
                <div class="chart-wrapper">
                    <canvas id="stockChart"></canvas>
                </div>
                <div class="footer">Generated by MCP Stock Analyzer</div>
            </div>
            
            <script>
                const ctx = document.getElementById('stockChart').getContext('2d');
                new Chart(ctx, {{
                    type: 'line',
                    data: {{
                        labels: {json.dumps(dates)},
                        datasets: [{{
                            label: '{ticker} Closing Price',
                            data: {json.dumps(closes)},
                            borderColor: '#38bdf8',
                            backgroundColor: 'rgba(56, 189, 248, 0.1)',
                            borderWidth: 2,
                            pointRadius: 2,
                            pointHoverRadius: 6,
                            tension: 0.3,
                            fill: true
                        }}]
                    }},
                    options: {{
                        responsive: true,
                        maintainAspectRatio: false,
                        interaction: {{ mode: 'index', intersect: false }},
                        plugins: {{
                            legend: {{ labels: {{ color: '#f8fafc' }} }}
                        }},
                        scales: {{
                            x: {{ ticks: {{ color: '#94a3b8' }}, grid: {{ color: '#334155' }} }},
                            y: {{ ticks: {{ color: '#94a3b8' }}, grid: {{ color: '#334155' }} }}
                        }}
                    }}
                }});
            </script>
        </body>
        </html>
        """
        
        # Save to a temporary file the user can easily click/open
        temp_dir = tempfile.gettempdir()
        filepath = os.path.join(temp_dir, f"{ticker.replace('.', '_')}_dashboard_{period}.html")
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
            
        return f"Interactive HTML dashboard incredibly generated and saved at:\nfile:///{filepath.replace(os.sep, '/')}\n\nTell the user they can copy-paste this path into their Chrome/Edge browser or Ctrl+Click it to view the interactive graph!"
        
    except Exception as e:
        return f"Error generating dashboard: {str(e)}"
